# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         AltaVista-BabelFish
version:      v42.0.2
version_from: BabelFish.pm
installdirs:  site
requires:
    Class::Std:                    0
    Class::Std::Utils:             0
    CPAN:                          0
    Locales::Language:             0
    LWP::UserAgent:                0
    version:                       0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
